DEFAULT_SECTIONS = [
    {"id": "announcement", "type": "announcement", "title": "Announcement Bar", "enabled": True,
     "data": {"text": "Free shipping above Rs 999", "background": "#111111", "color": "#ffffff"}},
    {"id": "header", "type": "header", "title": "Header", "enabled": True,
     "data": {"note": "Built from the global storefront header."}},
    {"id": "hero", "type": "hero", "title": "Hero Banner", "enabled": True,
     "data": {"headline": "Fuel Your Strength", "subheadline": "Build your legacy with premium supplements.",
              "buttonText": "Shop now", "buttonLink": "/marketplace.html", "alignment": "left",
              "backgroundImage": "", "backgroundVideo": "", "overlay": 55,
              "gradient": "linear-gradient(135deg,#111111,#2b2b2b)"}},
    {"id": "categories", "type": "categories", "title": "Categories", "enabled": True,
     "data": {"heading": "Categories", "subheading": "Shop by goal"}},
    {"id": "featured", "type": "featured", "title": "Featured Products", "enabled": True,
     "data": {"heading": "Featured Products", "subheading": "Hand-picked for performance", "count": 8,
              "sort": "popularity", "columns": 4, "showPrices": True, "showRatings": True,
              "showWishlist": True, "showQuickView": True, "showStock": True}},
    {"id": "deals", "type": "deals", "title": "Deals", "enabled": True,
     "data": {"heading": "Deals of the day", "subheading": "High value picks", "columns": 4}},
    {"id": "brands", "type": "brands", "title": "Brands", "enabled": True,
     "data": {"heading": "Brands", "subheading": "Trusted supplement names"}},
    {"id": "collections", "type": "collections", "title": "Collections", "enabled": True,
     "data": {"heading": "Collections", "subheading": "Goal-based collections"}},
    {"id": "testimonials", "type": "testimonials", "title": "Testimonials", "enabled": True,
     "data": {"heading": "Testimonials", "subheading": "What customers say"}},
    {"id": "newsletter", "type": "newsletter", "title": "Newsletter", "enabled": True,
     "data": {"heading": "Get 10% Off Your First Order",
              "copy": "Join for early access to new launches and restocks."}},
    {"id": "footer", "type": "footer", "title": "Footer", "enabled": True,
     "data": {"note": "Premium supplements, direct to your routine."}},
]
